---
title: "Stat 243 Final Project"
author: "Dan Shen, Letian Shi, Qianyi Yang, Xin Wang, Yue You"
subtitle: Multiple Factor Analysis R package
output:
  slidy_presentation: default
  html_document: default
  ioslides_presentation: default
  beamer_presentation:
    includes:
      in_header: header.tex
---

```{r, setup, include=FALSE}
library(knitr)
# smaller font size for chunks
knitr::opts_chunk$set(size = 'footnotesize')
options(width=78)
```
# Task allocation

  Dan Shen: mfa function and presentation
  
  Letian Shi: related methods and function/mfa function
  
  Qianyi Yang: Shiny app
  
  Xin Wang: R packaging and bootstrap function
  
  Yue You: Generic methods and plotting graphs in bootstrap function

# What is MFA?
Multiple factor analysis is an extension of principal component analysis (PCA) and aims to handle data set that measures sets of variables collected on the same observations.

- step 1: PCA of Each Data Table

  Each table is analyzed via a standard PCA. The weight of a table is obtained from the first singular value of its PCA. 
  
- step 2: GSVD of X

  All the normalized data tables are aggregated into a grand data table X that is analyzed via GSVD. This analysis will give a set of factor scores for the observations and loadings for the variables.
  
# Main function: mfa-part 1
We provide a main function mfa() in our package:
    
  _mfa(data, sets, ncomps=NULL, center=TRUE, scale=TRUE)_ where the arguments are:
  
- data: data set (matrix or data frame)
- sets: list of character or numeric vectors indicating the sets of variables 
- ncomps: integer indicating how many factors are to be extracted
- center: either a logical value or a numeric vector determining how column centering is perfromed
- scale: either a logical value or a numeric vector determining how the scaling of active variables is performed (after centering)

# Main function: mfa-part 2
mfa function should return on object of class *"mfa"* with the following elements:

- eigen: vector containing the eigenvalues 
- common_factor_scores: matrix of common factor scores
- partial_factor_scores: matrix of partial factor scores
- loadings: matrix of loadings
    
we also provide other information such as alpha, mass=rep(1/nrow,nrow), dim=ncomps and the complete scaled matrix for the user.

# Generic Methods   
print() method: displays 3 tables of basic information:

+ Table 1: Singular Values and Eigen Values;
+ Table 2. First Two Dimensions of Common Factor Scores;
+ Table 3. Partial Factor Scores of Any Assessor.

plot() method: displays 4 graphs with users' choice of any two dimenstions:

+ Graph 1: Common Factor Scores;
+ Graph 2: Partial Factor Scores;
+ Graph 3: Loadings rescaled to variance = eigen values;
+ Graph 4: Partial Factor Scores & rescaled Loadings together.

# Bootstrap
Function:

Graphs:

- Graph 1: Bootstrap ratio plot for Components 1 and 2.
- Graph 2: Bootstrap confidence ellipses plotted on Components 1 and 2.

# MFA package introduction

# Shiny App
We develop a shiny app that provides an interactive visualizeation for the results from MFA. We provide
the user with six types of plots, and the user can select which plot to look at.

  - *a bar-chart of the eigenvalues* 
  - *a scatterplot of the common factor scores* 
  - *a scatter plot of the partial factor scores* 
  - *a scatter plot of the partial factor scores and the loadings* 
  - *a bar-chart of bootstrap ratios*
  - *a bootstrap confidence ellipses plot*

For the two scatter plots related to partial factor scores and loadings, the user can choose which two dimensions to plot by adjusting the slider bar, and the plots will update automatically.
